
package com.hlj.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CommonWSInterService", targetNamespace = "http://healerjean/", wsdlLocation = "http://localhost:8080/SpringWebService/services/CommonService?wsdl")
public class CommonWSInterService
    extends Service
{

    private final static URL COMMONWSINTERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.hlj.client.CommonWSInterService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.hlj.client.CommonWSInterService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/SpringWebService/services/CommonService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/SpringWebService/services/CommonService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMMONWSINTERSERVICE_WSDL_LOCATION = url;
    }

    public CommonWSInterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonWSInterService() {
        super(COMMONWSINTERSERVICE_WSDL_LOCATION, new QName("http://healerjean/", "CommonWSInterService"));
    }

    /**
     * 
     * @return
     *     returns CommonWSInter
     */
    @WebEndpoint(name = "CommonWSInterPort")
    public CommonWSInter getCommonWSInterPort() {
        return super.getPort(new QName("http://healerjean/", "CommonWSInterPort"), CommonWSInter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonWSInter
     */
    @WebEndpoint(name = "CommonWSInterPort")
    public CommonWSInter getCommonWSInterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://healerjean/", "CommonWSInterPort"), CommonWSInter.class, features);
    }

}
