
package com.hlj.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CommonWSInter", targetNamespace = "http://healerjean/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonWSInter {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.hlj.client.MapConvertor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReturnMap", targetNamespace = "http://healerjean/", className = "com.hlj.client.GetReturnMap")
    @ResponseWrapper(localName = "getReturnMapResponse", targetNamespace = "http://healerjean/", className = "com.hlj.client.GetReturnMapResponse")
    public MapConvertor getReturnMap(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setMapParam", targetNamespace = "http://healerjean/", className = "com.hlj.client.SetMapParam")
    @ResponseWrapper(localName = "setMapParamResponse", targetNamespace = "http://healerjean/", className = "com.hlj.client.SetMapParamResponse")
    public String setMapParam(
        @WebParam(name = "arg0", targetNamespace = "")
        MapConvertor arg0);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receiveOARequestFromTransfer", targetNamespace = "http://healerjean/", className = "com.hlj.client.ReceiveOARequestFromTransfer")
    @ResponseWrapper(localName = "receiveOARequestFromTransferResponse", targetNamespace = "http://healerjean/", className = "com.hlj.client.ReceiveOARequestFromTransferResponse")
    public String receiveOARequestFromTransfer(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
