package com.atguigu.day02_ws_cxf_spring.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2014-03-12T11:20:48.055+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "OrderWSImplService", 
                  wsdlLocation = "http://localhost/day02_ws_cxf_spring/orderws?wsdl",
                  targetNamespace = "http://ws.day02_ws_cxf_spring.atguigu.com/") 
public class OrderWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.day02_ws_cxf_spring.atguigu.com/", "OrderWSImplService");
    public final static QName OrderWSImplPort = new QName("http://ws.day02_ws_cxf_spring.atguigu.com/", "OrderWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/day02_ws_cxf_spring/orderws?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost/day02_ws_cxf_spring/orderws?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort() {
        return super.getPort(OrderWSImplPort, OrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderWS
     */
    @WebEndpoint(name = "OrderWSImplPort")
    public OrderWS getOrderWSImplPort(WebServiceFeature... features) {
        return super.getPort(OrderWSImplPort, OrderWS.class, features);
    }

}
